// Add invited guests here. The key is used in links like index.html?guest=gideon-kalanzi.
window.INVITE_GUESTS = {
  "gideon-kalanzi": "Gideon Kalanzi",
  "mrs.-nsereko-rose": "Mrs. Nsereko Rose",
  "ms.-linda-nambalirwa": "Ms. Linda Nambalirwa",
  "lillian-sonko": "Lillian Sonko",
  "mr.-and-mrs.-sekajja-arthur": "Mr. & Mrs. Sekajja Arthur",
  "ruth-mirembe": "Ruth Mirembe",
  "aunt-namala-berna": "Aunt Namala Berna",
  "mr.-and-mrs.-kawooya-wilberforce": "Mr. & Mrs. Kawooya Wilberforce",
  "mr.-and-mrs.-gayi-eric-kasule": "Mr. & Mrs. Gayi Eric Kasule",
  "kasujja-james-raymond": "Kasujja James Raymond",
  "simon-peter": "Simon Peter",
  "mr.-and-mrs.-mulindwa-john": "Mr. & Mrs. Mulindwa John",
  "jean-clement-sekiranda": "Jean Clement Sekiranda",
  "cissy-nansamba": "Cissy Nansamba",
  "deborah-arinaitwe": "Deborah Arinaitwe",
  "judith-atholere": "Judith Atholere",
  "gloria-lamunu": "Gloria Lamunu",
  "etot-james-lucas": "Etot James Lucas",
  "karugaba-joseph": "Karugaba Joseph",
    "ms-babirye-stella": "Ms. Babirye Stella",
  "ms-lamunu-gloria": "Ms. Lamunu Gloria",
  "mr-ssensozi-james": "Mr. Ssensozi James",
  "aunt-annet-nabuuma": "Aunt Annet Nabuuma",
  "mr-noah": "Mr. Noah",
  "aunt-cathy-wanyana": "Aunt Cathy Wanyana",
  "mr-and-mrs-sserubiri": "Mr. & Mrs. Sserubiri",
  "pastor-mukisa": "Pastor Mukisa",
  "mr-and-mrs-ssemanda": "Mr. & Mrs. Ssemanda",
  "mr-and-mrs-bwogi-tom": "Mr. & Mrs. Bwogi Tom",
  "mr-lukwata-andrew": "Mr. Lukwata Andrew",
  "ms-dorcus": "Ms. Dorcus",
  "mr-and-mrs-mutebi": "Mr. & Mrs. Mutebi",
  "mr-kirabo-eric": "Mr. Kirabo Eric",
  "mr-and-mrs-kawooya": "Mr. & Mrs. Kawooya",
  "aunt-joan-and-family": "Aunt Joan & Family",
  "kojja-masembe": "Kojja Masembe",
  "jajja-muwulya": "Jajja Muwulya",
  "mrs-kalinzi-spe": "Mrs. Kalinzi Spe",
  "jajja-lugasa-deo": "Jajja Lugasa Deo",
  "mr-and-mrs-kayita": "Mr. & Mrs. Kayita",
  "mr-and-mrs-tumusiime": "Mr. & Mrs. Tumusiime",
  "mr-and-mrs-bagenda-elijah": "Mr. & Mrs. Bagenda Elijah",
  "mr-and-mrs-bayrogera": "Mr. & Mrs. Bayrogera",
  "mr-kizito-vincent": "Mr. Kizito Vincent",
  "ms-allen-nakabuye": "Ms. Allen Nakabuye",
  "ssalongo-ne-nalongo-yiga": "Ssalongo Ne Nalongo Yiga",
  "mr-and-mrs-omongole": "Mr. & Mrs. Omongole",
  "ms-deborah-namatovu": "Ms. Deborah Namatovu",
  "ms-esther-nakamate": "Ms. Esther Nakamate",
  "aunt-nakalanzi": "Aunt Nakalanzi",
  "mr-and-mrs-ssemaganda": "Mr. & Mrs. Ssemaganda",
  "mr-luyombya-steven": "Mr. Luyombya Steven",
  "aunt-rose-nakajjubi": "Aunt Rose Nakajjubi"
};
